name: textbook
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
  - defaults
dependencies:
  - libgcc
  - gxx_linux-64
  - python                          
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2                         
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability  
  - alabaster
  - applaunchservices
  - argh
  - argon2-cffi
  - asn1crypto
  - astroid
  - astropy
  - async_generator
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.shutil_get_terminal_size
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blas
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - defusedxml
  - diff-match-patch
  - distributed
  - docutils
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - filelock
  - flake8
  - flask
  - freetype
  - fsspec
  - future
  - get_terminal_size
  - gettext
  - gevent
  - glib
  - glob2
  - gmp
  - gmpy2
  - greenlet
  - h5py
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - imagesize
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jdcal
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema