name: textbook
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
  - defaults
dependencies:
  - libgcc
  - gxx_linux-64
  - python                          
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2                         
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - alabaster
  - applaunchservices
  - argh
  - argon2-cffi
  - asn1crypto
  - astroid
  - astropy
  - async_generator
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.shutil_get_terminal_size
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blas
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - defusedxml
  - diff-match-patch
  - distributed
  - docutils
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - filelock
  - flake8
  - flask
  - freetype
  - fsspec
  - future
  - get_terminal_size
  - gettext
  - gevent
  - glib
  - glob2
  - gmp
  - gmpy2
  - greenlet
  - h5py
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - imagesize
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jdcal
  - jedi<0.16
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lcms2
  - libarchive
  - libcurl
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - liblief
  - libllvm10
  - libpng
  - libsodium
  - libspatialindex
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - llvm-openmp
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multipledispatch
  - nbclient
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - olefile
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - partd
  - path
  - path.py
  - pathlib2
  - pathtools
  - patsy
  - pcre
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - pluggy
  - ply
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - py
  - py-lief
  - pycodestyle
  - pycosat
  - pycparser
  - pycurl
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytables
  - pytest
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python-libarchive-c
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - readline
  - regex
  - requests
  - ripgrep
  - rope
  - rtree
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy==1.4.1
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tblib
  - terminado
  - testpath
  - tensorflow==2.2
  - tensorboard<2.3.0                  
  - tensorboard-plugin-wit        
  - tensorflow-datasets           
  - tensorflow-estimator<2.3.0          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability      
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - toolz
  - tornado<6
  - tqdm
  - traitlets
  - typing_extensions
  - ujson
  - unicodecsv
  - unixodbc
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xlrd
  - xlsxwriter
  - xlwt
  - xz
  - yaml
  - yapf
  - zict
  - zipp
  - docopt
  - ghp-import
  - gitdb
  - gitpython
  - jupyter-book
  - jupyter-cache
  - jupyter-sphinx
  - jupyter-server==1.1.0
  - latexcodec
  - markdown-it-py
  - myst-nb
  - myst-parser
  - nbconvert
  - nbdime
  - oset
  - pybtex
  - pybtex-docutils
  - pydata-sphinx-theme
  - smmap
  - sphinx-book-theme
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-panels
  - sphinx-thebe
  - sphinx-togglebutton
  - sphinxcontrib-bibtex
  - sphinxext-rediraffe
  - sphinx-multitoc-numbering
  - libgcc-ng